import {IBM_Plex_Mono, Space_Grotesk, EB_Garamond, Victor_Mono, Ubuntu_Mono} from "next/font/google";
import localFont from 'next/font/local'

export const IBMMono500 = IBM_Plex_Mono({weight: '600', subsets: ['latin']})
export const Grotesk400 = Space_Grotesk({weight: '400', subsets: ['latin']})
export const Grotesk700 = Space_Grotesk({weight: '700', subsets: ['latin']})
export const EBGaramond400 = EB_Garamond({weight: '400', subsets: ['latin']})
export const Village = localFont({src: './village.ttf'})
export const ToonyLineLine = localFont({src: './toonyline.otf'})
export const ToonyLineFill = localFont({src: './toonylinefill.otf'})
export const Alagard = localFont({src: './alagard.ttf'})
export const Ninety = localFont({src: './nineteeninentythree.otf'})
export const Gliker = localFont({src: './gliker.ttf'})
export const ChicagoBold = localFont({src: './chicago.ttf'})
export const ChicagoLight = localFont({src: './chicago_light.ttf'})
export const Mushy = localFont({src: './mushy.ttf'})
export const Victor = Victor_Mono({weight: '400', subsets: ['latin']})
export const Ubuntu = Ubuntu_Mono({weight: '400', subsets: ['latin']})
export const Cotton = localFont({src: './cotton.ttf', subsets: ['latin']})
export const SansFrans = localFont({src: './sansfrans.otf', subsets: ['latin']})
export const SansFransBold = localFont({src: './sansfransbold.otf', subsets: ['latin']})
export const Genty = localFont({src: './genty.ttf', subsets: ['latin']})
export const HelveticaRoman = localFont({src: './helveticaroman.ttf', subsets: ['latin']})
export const FairfaxItalic = localFont({src: './fairfaxitalic.ttf', subsets: ['latin']})
export const Bello = localFont({src: './bello.ttf', subsets: ['latin']})